### ISSUE TITLE
Buy & Sell v1 - Indie Mento

### ISSUE THREAD

**Issue by sissnad** [celo-org/mento2-model#70]
Replicate current Indie Mento setup for cUSD, cEUR and cREAL

### TODOs

- [ ] Abstract the exchange to support different quote stable assets
- [ ] Adapt actors and state update blocks to support all exchanges
- [ ] MarketPriceGenerator creates a market price for CELO/{eur,brl}
