### ISSUE TITLE
Prepare Github repo for open-sourcing

### ISSUE THREAD

**Issue by bowd** [celo-org/mento2-model#80]
### TODOs

- [ ] Write a few READMEs to explain the structure
- [ ] Setup an experiments structure that ties into the overall work streams
- [ ] Add experiment READMEs with content from the forum post
- [ ] Rename master to main
